version: "2"
run:
  concurrency: 4
  tests: true
linters:
  enable:
    - bodyclose
    - gocritic
    - gosec
    - godox
    - makezero
    - misspell
    - nakedret
    - revive
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings:
    godox:
      keywords:
        - TODO
        - FIXME
        - HACK
        - BUG
        - XXX
    staticcheck:
      checks:
        - "all"
        - -QF1008
        - -ST1000
