# https://taskfile.dev

version: "3"

tasks:
  # test utils: pass CLI args as task:test -- -v
  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}
  test:unit:
    cmds:
      - go test ./internal/... {{.CLI_ARGS}}
  test:int:
    cmds:
      - go test -tags=integration ./test/integration/... {{.CLI_ARGS}}
  test:e2e:
    cmds:
      - go test -tags=e2e ./test/e2e/... {{.CLI_ARGS}}
  test:clean:
    cmds:
      - go clean -testcache
  # build 'n' runs
  build:
    cmds:
      - go build -C cmd/neo4j-mcp -o ../../bin/ {{.CLI_ARGS}}
  run:
    dotenv: [".env.task"]
    cmds:
      - go run ./cmd/neo4j-mcp
  run:compiled:
    dotenv: [".env.task"]
    cmds:
      - ./bin/neo4j-mcp {{.CLI_ARGS}}
  # generation
  generate:
    cmds:
      - go generate ./...
  # dev tooling
  lint:
    cmds:
      - golangci-lint run
  # playground 'n' debugging
  inspect:
    dotenv: [".env.task"]
    cmds:
      - npx @modelcontextprotocol/inspector go run ./cmd/neo4j-mcp
  interactive-client:
    dotenv: [".env.task"]
    cmds:
      - go run ./client/... bin/neo4j-mcp
