# https://taskfile.dev

version: "3"

tasks:
  run:
    cmds:
      - go run ./cmd/neo4j-mcp
  build:
    cmds:
      - go build -C cmd/neo4j-mcp -o ../../bin/

  generate:
    cmds:
      - go generate ./...
  # pass CLI args as task:test -- -v
  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}
  test:unit:
    cmds:
      - go test ./internal/... {{.CLI_ARGS}}
  test:int:
    cmds:
      - go test -tags=integration ./test/integration/... {{.CLI_ARGS}}
  lint:
    cmds:
      - golangci-lint run
  inspect:
    cmds:
      - npx @modelcontextprotocol/inspector go run ./cmd/neo4j-mcp
