name: Build and Integration Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: "1.25.3"
      - run: go install go.uber.org/mock/mockgen@latest

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Run integration tests
        run: go test -v -tags=integration ./test/integration/...
        env:
          USE_CONTAINER: "false"
          NEO4J_PASSWORD: ${{ secrets.AURA_PASSWORD }}
          NEO4J_URI: ${{ secrets.AURA_URL }}
