name: License

on:
  workflow_call:

permissions:
  contents: read

jobs:
  license-header-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: "1.26.3"
      - name: Install addlicense
        run: go install github.com/google/addlicense@b289835c0741ba2fb92dd5f61af070e79c69a55e # v1.2
      - name: Run addlicense
        run: addlicense -f ./addlicense -check $(find . -name "*.go" -type f -print0 | xargs -0)
